// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace chess.spa.feature.tests.Features.ChessRules
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("King Rules")]
    public partial class KingRulesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "King.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "King Rules", "\tEnsure the rules of chess for kings are correctly enforced and implemented", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings can move one square diagonally")]
        public virtual void KingsCanMoveOneSquareDiagonally()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings can move one square diagonally", null, ((string[])(null)));
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "...K...."});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
#line 6
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table2, "Given ");
#line 15
 testRunner.When("I click the square at \"d4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("\"c5,e5,e3,c3\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("\"b6,f6,f2,b2\" have no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings move one square horizontally and vertically")]
        public virtual void KingsMoveOneSquareHorizontallyAndVertically()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings move one square horizontally and vertically", null, ((string[])(null)));
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "...K...."});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
#line 20
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table3, "Given ");
#line 29
 testRunner.When("I click the square at \"d4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("\"d5,d3,c4,e4\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("\"d6,d2,b4,f4\" have no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings cannot move in to check")]
        public virtual void KingsCannotMoveInToCheck()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings cannot move in to check", null, ((string[])(null)));
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table4.AddRow(new string[] {
                        "....r..."});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "...K...."});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "........"});
#line 34
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table4, "Given ");
#line 43
 testRunner.When("I click the square at \"d4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.Then("\"c5,c3\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
 testRunner.And("\"e3,e4,e5\" have no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings cannot be left in check by other pieces move")]
        public virtual void KingsCannotBeLeftInCheckByOtherPiecesMove()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings cannot be left in check by other pieces move", null, ((string[])(null)));
#line 47
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table5.AddRow(new string[] {
                        "....r..."});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "....R..."});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "....K..."});
#line 48
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table5, "Given ");
#line 57
 testRunner.When("I click the square at \"e4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
 testRunner.Then("\"e2,e3,e5,e6,e7\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.And("\"a4,b4,c4,d4,f4,g4,h4\" have no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings can castle king side")]
        public virtual void KingsCanCastleKingSide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings can castle king side", null, ((string[])(null)));
#line 61
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table6.AddRow(new string[] {
                        "....r..."});
            table6.AddRow(new string[] {
                        "........"});
            table6.AddRow(new string[] {
                        "........"});
            table6.AddRow(new string[] {
                        "....R..."});
            table6.AddRow(new string[] {
                        "........"});
            table6.AddRow(new string[] {
                        "........"});
            table6.AddRow(new string[] {
                        "....K..R"});
#line 62
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table6, "Given ");
#line 71
 testRunner.When("I click the square at \"e1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.Then("\"g1\" has destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.When("I click the square at \"g1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.Then("\"f1\" contains \"R\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
 testRunner.And("\"g1\" contains \"K\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings can castle queen side")]
        public virtual void KingsCanCastleQueenSide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings can castle queen side", null, ((string[])(null)));
#line 77
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table7.AddRow(new string[] {
                        "....r..."});
            table7.AddRow(new string[] {
                        "........"});
            table7.AddRow(new string[] {
                        "........"});
            table7.AddRow(new string[] {
                        "....R..."});
            table7.AddRow(new string[] {
                        "........"});
            table7.AddRow(new string[] {
                        "........"});
            table7.AddRow(new string[] {
                        "R...K..."});
#line 78
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table7, "Given ");
#line 87
 testRunner.When("I click the square at \"e1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
 testRunner.Then("\"c1\" has destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
 testRunner.When("I click the square at \"c1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.Then("\"d1\" contains \"R\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 91
 testRunner.And("\"c1\" contains \"K\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings cannot move next to each other white to move")]
        public virtual void KingsCannotMoveNextToEachOtherWhiteToMove()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings cannot move next to each other white to move", null, ((string[])(null)));
#line 93
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "..K.k..."});
            table8.AddRow(new string[] {
                        "........"});
            table8.AddRow(new string[] {
                        "........"});
            table8.AddRow(new string[] {
                        "........"});
            table8.AddRow(new string[] {
                        "........"});
            table8.AddRow(new string[] {
                        "........"});
            table8.AddRow(new string[] {
                        "........"});
            table8.AddRow(new string[] {
                        "........"});
#line 94
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table8, "Given ");
#line 103
 testRunner.When("I click the square at \"c8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.Then("\"d8\" has no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings cannot move next to each other black to move")]
        public virtual void KingsCannotMoveNextToEachOtherBlackToMove()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings cannot move next to each other black to move", null, ((string[])(null)));
#line 107
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "..K.k..."});
            table9.AddRow(new string[] {
                        "........"});
            table9.AddRow(new string[] {
                        "........"});
            table9.AddRow(new string[] {
                        "........"});
            table9.AddRow(new string[] {
                        "........"});
            table9.AddRow(new string[] {
                        "........"});
            table9.AddRow(new string[] {
                        "........"});
            table9.AddRow(new string[] {
                        "........"});
#line 108
 testRunner.Given("a custom board is used with \"black\" to move", ((string)(null)), table9, "Given ");
#line 117
 testRunner.When("I click the square at \"e8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 118
 testRunner.Then("\"d8\" has no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
