// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace chess.spa.feature.tests.Features.ChessRules
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("King Rules")]
    public partial class KingRulesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "King.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "King Rules", "\tEnsure the rules of chess for kings are correctly enforced and implemented", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings can move one square diagonally")]
        public virtual void KingsCanMoveOneSquareDiagonally()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings can move one square diagonally", null, ((string[])(null)));
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "...K...."});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
            table2.AddRow(new string[] {
                        "........"});
#line 6
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table2, "Given ");
#line 15
 testRunner.When("I click the square at \"d4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("\"c5,e5,e3,c3\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("\"b6,f6,f2,b2\" has no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings move one square horizontally and vertically")]
        public virtual void KingsMoveOneSquareHorizontallyAndVertically()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings move one square horizontally and vertically", null, ((string[])(null)));
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "...K...."});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
            table3.AddRow(new string[] {
                        "........"});
#line 20
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table3, "Given ");
#line 29
 testRunner.When("I click the square at \"d4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("\"d5,d3,c4,e4\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("\"d6,d2,b4,f4\" has no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings cannot move in to check")]
        public virtual void KingsCannotMoveInToCheck()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings cannot move in to check", null, ((string[])(null)));
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table4.AddRow(new string[] {
                        "....r..."});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "...K...."});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "........"});
            table4.AddRow(new string[] {
                        "........"});
#line 34
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table4, "Given ");
#line 43
 testRunner.When("I click the square at \"d4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.Then("\"c5,c3\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
 testRunner.And("\"e3,e4,e5\" has no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Kings cannot be left in check by other pieces move")]
        public virtual void KingsCannotBeLeftInCheckByOtherPiecesMove()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kings cannot be left in check by other pieces move", null, ((string[])(null)));
#line 47
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "....k..."});
            table5.AddRow(new string[] {
                        "....r..."});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "....R..."});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "........"});
            table5.AddRow(new string[] {
                        "....K..."});
#line 48
 testRunner.Given("a custom board is used with \"white\" to move", ((string)(null)), table5, "Given ");
#line 57
 testRunner.When("I click the square at \"e4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
 testRunner.Then("\"e2,e3,e5,e6,e7\" have destination highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.And("\"a4,b4,c4,d4,f4,g4,h4\" has no highlighting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
